# Code style
# https://scrutinizer-ci.com/docs/reviews/configure_automated_checks
checks:
  php: true

filter:
  excluded_paths:
    - "build/"
    - "tests/"

# Tests
# https://scrutinizer-ci.com/docs/configuration/build_reference

# build:
#   environment:
#     php:
#       version: '8.0'
#   requires:
#     - branch: master
#   nodes:
#     analysis:
#       tests:
#         override:
#           - php-scrutinizer-run

# Analysis
# https://scrutinizer-ci.com/docs/tools/external-code-coverage/

tools:
  external_code_coverage: true

# Code Style
# https://scrutinizer-ci.com/docs/configuration/coding_style

coding_style:
